import type { Product, Shop } from '../types/marketplace'

export const shopFixture: Shop = {
  id: 'shop-1',
  slug: 'test-shop',
  name: 'Test Shop',
  tagline: 'Made for testing',
  shortDescription: 'A short test shop description.',
  shopType: 'Testing',
  description: 'A test seller description.',
  email: 'seller@example.com',
  websiteUrl: 'https://test-shop.example',
  socialLinks: ['https://instagram.com/testshop'],
  address: 'Test Street 1',
  logoUrl: '/logo.jpg',
  bannerUrl: '/banner.jpg',
  categories: ['Home'],
  location: 'Test City',
  postalCode: '1000 AA',
  country: 'Netherlands',
  pickupAvailable: true,
  deliveryAvailable: true,
  localDeliveryFee: 5,
  internationalDeliveryFee: 10,
  freeDeliveryAbove: 50,
  openingHours: [
    { dayOfWeek: 1, isClosed: false, openTime: '10:00', closeTime: '18:00' },
  ],
  active: true,
  approved: true,
}

export const productFixture: Product = {
  id: 'product-1',
  shopId: '1',
  shopSlug: 'test-shop',
  shopName: 'Test Shop',
  name: 'Test Product',
  description: 'A useful test product.',
  price: 12.5,
  currency: 'EUR',
  category: 'Home',
  stock: 3,
  images: ['/one.jpg', '/two.jpg'],
  featured: true,
  sellerContact: {
    email: 'seller@example.com',
    phone: '+31 20 123 4567',
    whatsapp: '+31 6 1234 5678',
  },
}

export const secondShopFixture: Shop = {
  id: 'shop-2',
  slug: 'other-shop',
  name: 'Other Shop',
  tagline: 'A second seller',
  shortDescription: 'Another short description.',
  shopType: 'Testing',
  description: 'Another test seller description.',
  email: 'other-seller@example.com',
  logoUrl: '/logo2.jpg',
  bannerUrl: '/banner2.jpg',
  categories: ['Food'],
  location: 'Other City',
  country: 'Netherlands',
  pickupAvailable: true,
  deliveryAvailable: true,
  localDeliveryFee: 3,
  internationalDeliveryFee: 8,
  freeDeliveryAbove: 30,
}

export const secondProductFixture: Product = {
  id: 'product-2',
  shopId: '2',
  shopSlug: 'other-shop',
  shopName: 'Other Shop',
  name: 'Other Product',
  description: 'A product from a different shop.',
  price: 8,
  currency: 'EUR',
  category: 'Food',
  stock: 5,
  images: ['/three.jpg'],
  featured: false,
  sellerContact: {
    email: 'other-seller@example.com',
  },
}
